#!/bin/sh

# Run this every month to archive the usage database for that month.
# Use these handy crontab entries, since crontab, despite being built to
# run things at certain *times*, is not very good at dates.
#
# 55 23 30 4,6,9,11        * root /jffs/wrtbwmon/archive 
# 55 23 31 1,3,5,7,8,10,12 * root /jffs/wrtbwmon/archive
# 55 23 28 2               * root /jffs/wrtbwmon/archive

tag=$(date +"%Y-%m")

archivedir=/jffs/wrtbwmon/archive

[[ ! -d "$archivedir" ]] && mkdir -p $archivedir
echo "mv /tmp/usage.db $archivedir/usage.$tag"
mv /tmp/usage.db $archivedir/usage.$tag
